language: php

php:
    - "7.4"
    - "7.3"
    - hhvm
    - nightly

sudo: false

env:
    global:
        - XDEBUG_MODE=coverage

git:
    submodules: false

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

before_script:
    - make install

script:
    - make test





